### ISSUE TITLE
Simple Question about Data Preprocessing

### ISSUE THREAD

**Issue by zeinaabuaisheh** [akanazawa/cmr#13]
Hello,
I would like to train a model on ShapeNet with does not have neither foreground masks nor semantic annotations, what should I do and in which format I should save the data after annotation?

**Comment by akanazawa** [comment]
I haven't worked with Shapenets so others can add, but I'm sure in ShapeNet you can get foreground masks since the ground truth 3D is available (any renderer would give you a mask), not sure about the semantic annotations. The focus of this work is on datasets without any ground truth 3D models, so we didn't really look into this. 

Best,

A
